# default variables
# s3 bucket variables
bucket_name: thomas-nyambati-s3-web
deletion_policy: Retain

# account variables
region: us-east-1
key_pair: thomas-devops

# ec2 variables
instance_type: t2.micro
image: ami-e3e8eb89
image_name: thomas-nyambati-image
instances_min_size: 1
instances_max_size: 2
shh_block: 0.0.0.0/0
cool_down: 60

#vpc variables
stack_name: thomas-nyambati-cloudformation
vpc_cidr_block: 10.0.0.30/16

# SNS protocols
sns_endpoint: thomas.nyambati@andela.com
protocol: email